style: none
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/miawinter98/Wave
options:
  tag_filter_pattern: '^(v|alpha-|beta-)'
  issues: 
    prefix:
      - '#'
  commits:
    filters:
      Type:
        - Added
        - Changed
        - fixed
        - Implemented
        - Improved
        - Localized
  commit_groups:
    # title_maps:
    #   feat: Features
    #   fix: Bug Fixes
    #   perf: Performance Improvements
    #   refactor: Code Refactoring
  header:
    pattern: "^((\\w+)\\s.*)$"
    pattern_maps:
      - Subject
      - Type
  notes:
    keywords:
      - BREAKING CHANGE